services:
  file-organizer:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - caddy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SOLO_API_KEY=${SOLO_API_KEY}
      - MODEL_VISION=${MODEL_VISION}
      - MODEL_TEXT=${MODEL_TEXT}
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_CLASSIFY=${MODEL_CLASSIFY}
      - MODEL_TAGGING=${MODEL_TAGGING}
      - MODEL_FOLDERS=${MODEL_FOLDERS}

      - OLLAMA_API_URL=${OLLAMA_API_URL}

networks:
  caddy:
    external: true