services:
  file-organizer:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - caddy
    labels:
      caddy: organize.zagreus.eu.org
      caddy.reverse_proxy: "{{upstreams 3000}}"
    environment:
      - DDC_API_KEY=${DDC_API_KEY}
      - ZUKI_API_KEY=${ZUKI_API_KEY}
      - FRESED_API_KEY=${FRESED_API_KEY}
      - HELIX_API_KEY=${HELIX_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SOLO_API_KEY=${SOLO_API_KEY}
      - MODEL_VISION=${MODEL_VISION}
      - MODEL_TEXT=${MODEL_TEXT}
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_CLASSIFY=${MODEL_CLASSIFY}
      - MODEL_TAGGING=${MODEL_TAGGING}
      - MODEL_FOLDERS=${MODEL_FOLDERS}
      - OLLAMA_API_URL=${OLLAMA_API_URL}
networks:
  caddy:
    external: true
